Christian ubani
chikechris/Sprint-Challenge--JavaScript pull request #1
Opened 2019-06-14 18:36 UTC by chikechris

Finished the JavaScript Sprint Challenge project work.

2019-06-14 19:05 UTC, Marguelgtz requested changes
# Good Sprint Christian

It looks that you understand most of the objectives for this week, It look like you are confused about the forEach method and you are trying to replicate a for loop when using it. the `forEach` method works exactly the same way as `.map()` the only difference is that returns a copy of your array when `forEach` doesn't. Please go back and refactor the instances where you use the `forEach` method

## Observations 
- Good Commits
- Problems with the `forEach` methods

2019-06-14 19:05 UTC, Marguelgtz commented on challenges/functions.js
> +// Explanation:
Good example of closure christian however you are missing the explanation of why the nested function can access the external variable

2019-06-14 19:05 UTC, Marguelgtz commented on challenges/objects-arrays.js
> +  contactInfo.push(graduates[i]["first_name"] + " " + graduates[i]["email"]);
on this `forEach` even though it still works you are over complicating the process here. I see you are replicating what is happening on a for loop. Your `forEach` works the same way the `map` does on the first request. you don't need to specify the index of the graduate array to get each item since for each is doing that for you with the argument you give your call back function
```
const contactInfo = []
// graduate would be each item of your array
graduates.forEach(graduate => {
  contactInfo.push(graduate.first_name + " " + graduate.email);
```

2019-06-14 19:05 UTC, Marguelgtz commented on challenges/objects-arrays.js
> +    uni.push(graduates[j].university);
Same as in the request two, you are trying to replicate a for loop when for each does this for you. also take a look at the `.includes()` method to find the `Unis`

2019-06-17 15:12 UTC, Marguelgtz approved these changes
Goo job fixing your array methods Christian 👍

2019-06-17 15:14 UTC, merged

2019-06-17 16:21 UTC, Marguelgtz approved these changes
Good job refactoring your array methods Christian 👍

2019-06-17 16:35 UTC, chikechris commented
Thanks a lot.

On Mon, Jun 17, 2019 at 11:14 AM Marguelgtz <notifications@github.com>
wrote:

> Merged #1
> <https://github.com/chikechris/Sprint-Challenge--JavaScript/pull/1> into
> master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chikechris/Sprint-Challenge--JavaScript/pull/1?email_source=notifications&email_token=AI2QQJHP2CWFBTJRYHUYGFLP26S6RA5CNFSM4HYMCIGKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSAPSSUI#event-2417961297>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AI2QQJHLF2B76RD57G2WV4DP26S6RANCNFSM4HYMCIGA>
> .
>